#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("HowlOut.Droid.Resource", IsApplication=true)]

namespace HowlOut.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ModernHttpClient.Resource.String.library_name = global::HowlOut.Droid.Resource.String.library_name;
			global::Plugin.LocalNotifications.Resource.Drawable.plugin_lc_smallicon = global::HowlOut.Droid.Resource.Drawable.plugin_lc_smallicon;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040005
			public const int blueDark = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int blueLight = 2130968582;
			
			// aapt resource value: 0x7f040004
			public const int bluePrimary = 2130968580;
			
			// aapt resource value: 0x7f040009
			public const int grayDark = 2130968585;
			
			// aapt resource value: 0x7f040008
			public const int grayLight = 2130968584;
			
			// aapt resource value: 0x7f04000a
			public const int grayMedium = 2130968586;
			
			// aapt resource value: 0x7f040007
			public const int grayPrimary = 2130968583;
			
			// aapt resource value: 0x7f040003
			public const int greenDark = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int greenLight = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int greenPrimary = 2130968577;
			
			// aapt resource value: 0x7f04000b
			public const int purpleDark = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int purplePrimary = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int textPrimary = 2130968589;
			
			// aapt resource value: 0x7f040000
			public const int white = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int banner_blade = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int banner_controller = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int banner_donut = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int banner_fodbold = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int banner_golf = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int banner_gravid = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int banner_hjort = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int banner_kaffe = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int banner_marked = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int banner_publikum = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int banner_scrabble = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int banner_skak = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int banner_skater = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int banner_skovsoe = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int banner_surf = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int banner_vinglas = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int gradiant_bg = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int howlouticongrown = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int howloutsplash = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int ic_add = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int ic_calender = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int ic_chevron = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int ic_event = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int ic_explore = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int ic_public = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int ic_refresh = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int ic_search = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int icon = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int plugin_lc_smallicon = 2130837532;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public const int library_name = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050001
			public const int GrayTheme = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int PurpleTheme = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
